# REST Client configuration
book-api/mp-rest/url=http://localhost:8080/llm-jakarta

quarkus.http.port=8888

quarkus.package.jar.type=uber-jar
quarkus.log.file.enable=true
quarkus.log.file.path=bookstore-quarkus.log